### ISSUE TITLE
Format single conditional + LastStmt (`return/break`) "guard" statements on a single line?

### ISSUE THREAD

**Issue by JohnnyMorganz** [JohnnyMorganz/StyLua#161]
Its common to use single conditional statements + returns to act as guards/short circuits in code:
```lua
function foo(a, b, c)
    if a == "foo" then return true end
    if a == "bar" then return false end
    if not b then return end

    -- ...

    for i,v in pairs() do
        if calculateSomething(i) then break end
        -- ...
    end
end
```

Currently, however, StyLua will expand each conditional block with something like:
```lua
function foo(a, b, c)
    if a == "foo" then
        return true
    end
    if a == "bar" then
        return false
    end
    if not b then
        return
    end

    -- ...
end
```
which might be making it unnecessarily longer and more verbose. Having them on a single line seems cleaner and more elegant.
Should we keep these "guard" conditions on a single line? Prettier also allows this with `if (foobar) return;` etc.

Some points that we will enforce if this happens:
- We will only allow inlined `if condition then ... end` blocks. If the if statement contains an `elseif` or `else`, it will not be inlined.
- No other blocks (`while`/`do`/`for ... do ... end`) will be formatted as such, it does not make sense to do so.
- The body of the if statement must only be a LastStmt (`return/break/continue`) - `if condition then x = x + 1 return end` is not allowed.
- If the whole statement (`if condition then return end`) surpasses the column width, we will not inline the statement.
- If the `condition` in `if condition then` spans multiple lines, we will not inline the statement.
- If the return value(s) in `if condition then return ... end` span multiple lines, we will not inline the statement.
- If the statement contains any internal comments (not leading/trailing the whole statement), we will not inline the statement.

**Comment by lithammer** [comment]
Unsure if I should create a separate issue for this or not. But similarly, it would be nice to allow functions with empty bodies on one line as well.

```lua
function() end
```

**Comment by JohnnyMorganz** [comment]
> Unsure if I should create a separate issue for this or not. But similarly, it would be nice to allow functions with empty bodies on one line as well.
> 
> 
> 
> ```lua
> 
> function() end
> 
> ```

Hm yeah I agree, that would probably be wise too.

Would a similar thing also be useful for `while/for/do` blocks as well I wonder? Although it's unlikely those would be present, and are probably a sign of incorrect/missing code - keeping those multi line might make them more noticeable.

**Comment by lithammer** [comment]
> Would a similar thing also be useful for `while/for/do` blocks as well I wonder? Although it's unlikely those would be present, and are probably a sign of incorrect/missing code - keeping those multi line might make them more noticeable.

I think I would prefer to keep those multi line. They don't really make sense anyway. I can't think of a single valid use-case 🤔

**Comment by tjdevries** [comment]
I would definitely turn this on if it was an option.

I think the reasoning with only `LastStatement`s seems good to me.

**Comment by JohnnyMorganz** [comment]
I think I'm going to go ahead with this, as personally I prefer this style to the expanded version as it makes the code less verbose imo. I think its also quite a common style, so hopefully this isn't too big of a hit - probably won't make it optional though

**Comment by lithammer** [comment]
I suppose an another option is to just not format blocks like this at all? Only explode if the body contains multiple expressions:

```diff
-if foo then local bar = 123; print(bar) end
+if foo then
+  local bar = 123
+  print(bar)
+end
```

But leave both of these alone:

```lua
if foo then return "bar" end
```

```lua
if foo then
  return "bar"
end
```

**Comment by JohnnyMorganz** [comment]
> Not sure if possible. But another option is to just not format blocks like this at all...?

It would be *possible*, but I'm not sure if it would be ideal - its almost just a hidden option/configuration.
We actually do something similar to what you mentioned for table constructors, where if there is a newline present in between the start brace and the first field, we keep it multiline - even if its under the column width.
Prettier also does this for their JavaScript objects, but they point out a very valid issue about formatting reversibility - https://prettier.io/docs/en/rationale.html#multi-line-objects - to quote:
> What does reversible mean? Once an object literal becomes multiline, Prettier won’t collapse it back. If in Prettier-formatted code, we add a property to an object literal, run Prettier, then change our mind, remove the added property, and then run Prettier again, we might end up with a formatting not identical to the initial one. This useless change might even get included in a commit, which is exactly the kind of situation Prettier was created to prevent.

The same issue would also apply here if we ignored formatting for these blocks (imagine adding a statement before the return, stylua expands it multiline, but then you don't actually want it anymore, but rather than collapsing back again, it now stays multiline)

I think for this I'm just going to enforce a consistent style depending on the AST, excluding any direct or indirect user input.

**Comment by JohnnyMorganz** [comment]
Hm, this is a slightly bigger change in style than I realised.
There are some cases where this kind of if statement is common, but its not *really* acting as a guard, its just part of the general program flow
```lua
function foo()
    for i,v in pairs()
        -- lots of code here

        if failureCase then
            return false
        end
    end

    -- continue onwards
end
```
In these cases, formatting the if statement on a single line looks a bit odd to me (the most noticable example I saw was a large chunk of code, with a single if statement at the end).
I would normally expect these single-line guard-style statements at the beginning of a block, so one possible alternative would be to only format if the statement is at the beginning, but this makes the formatting style a bit more complex - I would rather just have a simple way of style.

I don't particularly want to add any sort of configuration or indirect choice based on the way the user had it currently formatted to solve this.

Going to think on this a bit more, and decide whether the pros in the "guard" style outweigh its side-effects in the rest of the code.

**Comment by tjdevries** [comment]
Guard style might only apply when the outer scope is not a loop? Not sure if there is some hard-and-fast rule we could do like that, but that might make it simpler, yet not affect those other situations.

**Comment by JohnnyMorganz** [comment]
> Guard style might only apply when the outer scope is not a loop? Not sure if there is some hard-and-fast rule we could do like that, but that might make it simpler, yet not affect those other situations.

I think the issue also happens even when the scope is not a loop, it was just an example above.

I definitely want this, I feel like it looks nicer to read collapsed, I just need to figure out a good heuristic here (or just bite the bullet and apply it everywhere). Suggestions definitely welcome!

**Comment by JohnnyMorganz** [comment]
As with other things, I think it would be better seeing this in the real world.
I've pushed a branch `singleline-if-2` which implements this everywhere, as originally designed.

For people interested, it would be awesome if you could try this out in your free time and get back to me on your thoughts:
```
cargo install --git https://github.com/JohnnyMorganz/StyLua.git --branch singleline-if-2
```
I'm interested to know if all the changes made in this style look reasonable to you, and if there's anything specific you might want to see different.

**Comment by tjdevries** [comment]
Ha, funny that you just pushed this. @conni2461 and I were just talking about this issue on stream. I will try and take a look this week.

**Comment by Conni2461** [comment]
I tested it just now by throwing it at our telescope code base and it looked great. I haven't found a single line that was formatted wrong in that diff.

Thanks :)

**Comment by matthargett** [comment]
I wonder if we should revisit this in light of the if-expressions syntax being available (https://github.com/Roblox/luau/blob/master/docs/_pages/syntax.md#if-then-else-expressions). Given the examples are all on one line (and they're within even an 80 column line budget), it seems like we may want to afford both single-line guard and if-expression syntax in the same implementation sweep.

**Comment by MagiMaster** [comment]
I'm slightly negative on this, but I don't have one strong reason for that, just a few weak ones.

* We decided against single line functions because they can lead to some actual readability-related errors. The example in the style guide is: `Rodux.Store.new(function(state) return state, mockState end, nil)`. Even if you know that new here takes three arguments, it's still hard to spot the issue. Now, guard statements aren't functions, but as evidenced above it does open the door to "why not other blocks." (Again, not a very strong reason. Also, strong typing would help catch these.)
* As is, any LastStmt's will be the first token on the line, which makes them easy to spot. That's similar to why we suggest putting the operators at the beginning of the line when you break a long expression up, and a couple other things.
* I don't think we make any other exceptions for the general one statement per line rule. One line empty functions aren't allowed mainly for this reason. (Though like I mentioned above, one line functions are more of an issue than one line ifs for other reasons.)
* Keeping the number of lines down is not a consideration in any of the existing style rules, but it's also not explicitly something we're avoiding, if that makes sense.
* If-then expressions are pretty similar, true, but there's enough differences that they deserve separate treatment.

I'll try and see if I can find some more concrete examples for or against, but since next week is Thanksgiving here, it might take me a bit.

**Comment by MagiMaster** [comment]
After looking at some of the output from the PR, it's not doing anything surprising, but I do have a couple more comments:

- If this were implemented, I'd suggest making sure there's a newline after the block of guards. You've done that manually in all the examples, but in cases where the currently expanded guard looks fine without the newline, the collapsed guard gets a bit lost. More-so the more lines around it. (Not quite sure how technically feasible that is to automate though, as there's a lot of edge cases.)
```
local function sortFunc(a, b)
    if a.rank == b.rank then return a.name:lower() < b.name:lower() end
    return a.rank < b.rank
end
```

- It feels really inconsistent to have some one-line-body ifs collapsed and not others.
```
local function updateStatus(value):
    if statusDebounce then return end
    if status ~= value then
        status = value
    end
end
```

- The examples so far are for short conditions and simple returns, but the longer either of those are (without running into the line length limit) the more the return gets lost.
```
if not status or status == ERROR or status == FAILED then return if flag() then FAILED else ERROR end
```

- The cases where this does best are when you do have several guards right at the top of a function (or even a function that is essentially all guards), but these aren't all that common. Usually, you only have one or two and this doesn't make a big difference.
```
local function getTarget(model)
    if not model then return end
    if model.PrimaryPart then return model.PrimaryPart end
    if model:FindFirstChild("HumanoidRootPart") then return model:FindFirstChild("HumanoidRootPart") end
    return model:FindFirstChildWhichIsA("BasePart")
end
```

**Comment by JohnnyMorganz** [comment]
I definitely agree that single line guards do best at the beginning of blocks, that *could* be a heuristic we employ but it might be quite confusing for someone if on one line it gets formatted on a single line, then a few lines later it gets forced onto multiple lines, and they didn't know this heuristic existed.

The longer the line gets, it definitely loses readability - in both your first and third example I would personally be doing it multiline.

Personally, I'm also leaning towards the against side. The current way (expand everything) works and has been "accepted" by people who have adopted stylua so far, and leaving it like that is easier.
Expanding everything vs collapsing everything depends on if we value overall readability more vs making the code "look nice". In my mind, currently, the benefits of overall readability in these more complex examples outweigh the costs of these guard statements looking more verbose when expanded.

**Comment by LastTalon** [comment]
> In my mind, currently, the benefits of overall readability in these more complex examples outweigh the costs of these guard statements looking more verbose when expanded.

I think this should be an important part of the formatting philosophy going forward. Its important to remember that some things we do when writing code is a compromise we don't need to make when we can automate the formatting. We can make things very readable even when writing them that way would normally be annoying.

**Comment by arnoson** [comment]
I still would love to see this. I think your first example shows how extremely verbose multiple guards can get. But I might me a bit biased because I mainly code in js/ts and use short return guards with prettier a lot. Although prettier only allows them if you omit the brackets `if (a === 'fuu') return false`, which you can't do in lua.

**Comment by JohnnyMorganz** [comment]
https://github.com/JohnnyMorganz/StyLua/pull/479 adds support for this behind an option flag. The PR is not guaranteed to be accepted however.
If you are still interested in this, please try it out and let me know how it works.

**Comment by arnoson** [comment]
great!
unfortunately I can't compile the new version: (changed my path to `<USER>` in the error log)
```sh
   Compiling stylua v0.13.1 (<USER>\.cargo\git\checkouts\stylua-fc4a1ea291bc99bb\550425c)
error[E0599]: no variant or associated item named `BlockEnd` found for enum `EndTokenType` in the current scope
   --> src\formatters\stmt.rs:438:82
    |
438 |         let end_token = format_end_token(ctx, if_node.end_token(), EndTokenType::BlockEnd, shape)    |                                                                                  ^^^^^^^^ variant or associated item not found in `EndTokenType`
    |
   ::: src\formatters\general.rs:26:1
    |
26  | pub enum EndTokenType {
    | --------------------- variant or associated item `BlockEnd` not found here

For more information about this error, try `rustc --explain E0599`.
error: could not compile `stylua` due to previous error
```

**Comment by JohnnyMorganz** [comment]
> great! unfortunately I can't compile the new version: (changed my path to `<USER>` in the error log)
> 
> ```shell
>    Compiling stylua v0.13.1 (<USER>\.cargo\git\checkouts\stylua-fc4a1ea291bc99bb\550425c)
> error[E0599]: no variant or associated item named `BlockEnd` found for enum `EndTokenType` in the current scope
>    --> src\formatters\stmt.rs:438:82
>     |
> 438 |         let end_token = format_end_token(ctx, if_node.end_token(), EndTokenType::BlockEnd, shape)    |                                                                                  ^^^^^^^^ variant or associated item not found in `EndTokenType`
>     |
>    ::: src\formatters\general.rs:26:1
>     |
> 26  | pub enum EndTokenType {
>     | --------------------- variant or associated item `BlockEnd` not found here
> 
> For more information about this error, try `rustc --explain E0599`.
> error: could not compile `stylua` due to previous error
> ```

Sorry! Not sure how I didn't notice that. Should be fixed now

**Comment by arnoson** [comment]
Thanks, now it works!
I really like it so far (allthough I haven't got a huge codebase to test it on). My main usecase will be return guards and this seems to work well, so I would be really happy to have this option in stylua

**Comment by JosefLitos** [comment]
I still cannot get this working. The readme also mentions only `Always|ConditionalOnly|FunctionOnly|Never` and no `LastStmt`. How can I get the single line `if`s for LastStmt only?

**Comment by JohnnyMorganz** [comment]
@JosefLitos can you show the code you are trying to format that is not working correctly, with the settings used?

IIRC, we now collapse "simple" statements rather than just "laststmt", where "simple" refers to either just a laststmt in the body (return / break), a function call, or a one variable assignment

**Comment by JosefLitos** [comment]
> we now collapse "simple" statements rather than just "laststmt"

That is my very issue. I see in many codebases, in which I try to contribute, that they have `collapse_simple_statements = "Never"`, yet they collapse all conditional `return`s, but not every "simple" statement.

**Comment by JohnnyMorganz** [comment]
Do you have an example codebase? That doesn't sound correct

**Comment by JosefLitos** [comment]
[this PR](https://github.com/ibhagwan/fzf-lua/pull/1205) is the most recent one I found myself in this situation.

**Comment by JohnnyMorganz** [comment]
> Although I have sylua.toml I’m still using lua_ls to do the formatting.

This comment in that PR explains it - they are not using stylua
